-- Ibrahim Oztas
-- 103577332

CREATE DATABASE Build_and_Query_Challenge_Resit_2;

USE Build_and_Query_Challenge_Resit_2;

/* Task 1 Convert ERD to Relational Schema

Order(DateTimePlaced, DeliveryAddress)
PK (DateTimePlaced)

OrderLine(Qty)

Client(ClientID, Name, Phone)
PK (ClientID)

MenuItem(ItemID, Description, ServesPerUnit, UnitPrice)
PK (ItemID)

Organisation(OrgID, OrganisationName)
PK (OrgID)
--

*/


















